### ISSUE TITLE
Controlar accesos a rutas por rol

### ISSUE THREAD

**Issue by cristianbarbaro** [mateodurante/WebScrub#1]
Las rutas que solo pueden acceder determinados users dados el rol pueden ser accedidas si se las escribe en el campo de url del navegador, aunque no son visibles desde el HTML.

**Comment by cristianbarbaro** [comment]
Para accederlas ahora tiene que ser administrator y tener ASN. Se debería controlar solamente que tenga ASN. El superuser solo debería ser para acceder al panel de administracion de django.

**Comment by mateodurante** [comment]
Solucionado en la ultima version
